add bin support for JDK 6 and before
vjkoskela/jdk-wrapper pull request #20
Opened 2017-05-13 19:23 UTC by coreen

using linux download as no option for macos in those legacy versions

2017-05-14 03:00 UTC, vjkoskela requested changes

2017-05-14 03:00 UTC, vjkoskela commented on .travis.yml
> +  - EXPECTED_VERSION=1.6.0_38 JDKW_VERSION=6u38 JDKW_BUILD=b05
Please add `JDKW_VERBOSE=1` to this in case it needs to be debugged

2017-05-14 03:00 UTC, vjkoskela commented on jdk-wrapper.sh
> +# JDK 6 and before use .bin extension, note no specific macosx download available for these versions (using linux)
So you're saying versions equal to and prior to JDK6 for Linux only used a bin format? And only a bin format?

It looks like it was a bin but that also wrapped an rpm:

http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase6-419409.html

Can you make the comment a little clearer?

2017-05-14 03:00 UTC, vjkoskela commented on jdk-wrapper.sh
> +  extension="bin"
If my understanding above is correct then you should nest this an os check for linux before doing the version check and then default to bin if both are true.

Please also add an asterisk to line 71 and describe this exception as a foot-note in the header comment and do the same in the Configuration section of the README.md file.

2017-05-14 03:00 UTC, vjkoskela commented on jdk-wrapper.sh
> +if [ "${JDKW_VERSION:2:1}" -le "6" ]; then
This doesn't work.

I think you're looking for the prefix pattern match to digits. For example, if the Java version were ever 60u110 you wouldn't want to treat it as version 6. So we need to either extract the `60` (numeric prefix) or dump the suffix (starting at `u`).

Something like `${JDKW_VERSION%%u*}` should do it but I haven't test it thoroughly.

2017-05-14 03:00 UTC, vjkoskela commented
Thanks this is great!

2017-05-28 18:56 UTC, coreen commented on jdk-wrapper.sh
> +# JDK 6 and before use .bin extension, note no specific macosx download available for these versions (using linux)
There are 2 options for download, a regular `.bin` and an rpm-wrapped `.bin`. I've updated the comment to mention the optionally wrapped rpm as another supported option for the `.bin` extension download.

2017-05-28 18:56 UTC, coreen commented on jdk-wrapper.sh
> +  extension="bin"
Adding the `.bin` extensions here was so even MacOS users would be able to use JDK 6 and before versions. Nesting under Linux will nullify that.

2017-06-01 01:34 UTC, coreen commented
Turns out Oracle pushed a change recently that forces users to login in order to download JDK 6 and 7 versions, so this PR will no longer work. Announcement in screenshot below or at http://www.oracle.com/technetwork/java/javase/archive-139210.html
![screen shot 2017-05-31 at 6 32 10 pm](https://cloud.githubusercontent.com/assets/6006946/26660853/9470a27c-462f-11e7-92c1-fc3c1fcb8bee.png)

2017-06-01 01:34 UTC, closed without merging